Create user details endpoints
nicuvlad7/yonderful pull request #22
Opened 2022-03-16 21:06 UTC by MadalinaMo

User details endpoints created respecting the latest requests.

2022-03-17 06:41 UTC, MihaiYonder commented on api/Controllers/UserController.cs
> +        public async Task<IActionResult> PutUser(User user)
Some empty spaces above and below the PUT method. These need to be removed.

2022-03-17 06:45 UTC, MihaiYonder commented on api/Service/UserService.cs
> +        var newUser = new User
Since there's already a User object received as a parameter, this new assignment looks redundant and should be removed.

2022-03-17 06:49 UTC, MihaiYonder commented on api/Service/UserService.cs
> +        existingUser.PhoneNo=user.PhoneNo;
One quick note here: for better code legibility you should leave spaces between and after the assignment operator. It makes it easier for others to read the code you wrote.
EG: existingUser.Email = user.Email
I've seen this somewhere else as well, I think in the Role enum.

2022-03-18 13:41 UTC, larisaChh commented on api/Controllers/UserController.cs
> +      return Ok(_mapper.Map<UserDto>(user));
The UserDto now also contains the password.
I do not think that this should be sent to the FE when getting user info.
Maybe you should consider creating a new dto - UserDetailsDto - that does not contain the password

2022-03-18 13:47 UTC, larisaChh commented on api/Extensions/ApplicationServiceExtensions.cs
> -            services.AddScoped<ICategoryService, CategoryService>();
why are these deleted? aren't they used by your colleagues?

2022-03-18 13:47 UTC, larisaChh commented on api/Extensions/ApplicationServiceExtensions.cs
> -            services.AddAutoMapper(typeof(CategoryMappings));
why is this deleted? isn't it used?

2022-03-18 13:51 UTC, larisaChh commented on api/Service/UserService.cs
> +      existingUser.Password = hashing.HashToString(user.Password);
the password will not be updated in this call

2022-03-18 13:52 UTC, larisaChh commented on api/Service/UserService.cs
> +      existingUser.Email = user.Email;
email cannot be modified for any user

2022-03-18 13:54 UTC, larisaChh commented on api/Service/UserService.cs
> +      existingUser.UserRole = user.UserRole;
role will not be updated in this call

2022-03-18 13:56 UTC, larisaChh commented on api/Service/UserService.cs
> +    public async Task<User> PutUser(User user)
Here only the
name, phone and profession should be updated, since these are the only editable fields by the user on the my profile page.

2022-03-21 13:08 UTC, larisaChh commented on api/Controllers/UserController.cs.orig
> +using System;
What is this file? Do we need it?

2022-03-21 14:23 UTC, meda-racasan requested changes

2022-03-21 14:23 UTC, meda-racasan commented on api/Controllers/UserController.cs
> +    {
`PutUser` method from the Controller should receive an `UserDTO` parameter

2022-03-21 14:23 UTC, meda-racasan commented on api/Service/IUserService.cs
> +  }
Make sure you are formatting the code with the same settings for tab (4 spaces). It looks like your editor formats with 2 spaces and each time you format a file you'll get more changes than needed.

![image](https://user-images.githubusercontent.com/101350955/159027202-e0728082-45e3-4d5b-bb33-25eaef7f432d.png)

2022-03-21 14:23 UTC, meda-racasan commented on api/Controllers/UserController.cs.orig
> +using System;
This .cs.orig file should be deleted

2022-03-22 12:49 UTC, merged