Initial commit
nicuvlad7/yonderful pull request #49
Opened 2022-03-27 16:41 UTC by MadalinaMo

Create Get All Future Events Endpoint

2022-03-28 09:57 UTC, meda-racasan requested changes

2022-03-28 09:57 UTC, meda-racasan commented on api/Controllers/FutureEventsController.cs
> +		{
Move this logic in the EventsController, as discussed at the planning meeting.

2022-03-28 17:59 UTC, meda-racasan requested changes

2022-03-28 17:59 UTC, meda-racasan commented on api/Service/FutureEventsService.cs
> +		public async Task<IList<Event>> GetFutureEventList()
Move this method under EventsService and delete this service

2022-03-29 05:16 UTC, MihaiYonder approved these changes
Looks good now!

2022-03-29 05:39 UTC, merged